### PR TITLE
Compatibility with Piwigo 12

### PR DESCRIPTION
**Pull request by MatthieuLP**

### CODE REVIEW

**Comment by max-ima** [comment]
No

**Comment by plegall** [comment]
@Eric-Piwigo did you get the time to check this?

**Comment by Eric-Piwigo** [comment]
Sorry Pierrick, I am unable to maintain any of the Piwigo related projects. Not enough free time. If anyone wants to continue them, no worries for me.

**Comment by plegall** [comment]
Allright, don't worry. Can you transfer your repository to the "Piwigo" organization. We will take care of it :-)

**Comment by Eric-Piwigo** [comment]
Done as well for all my piwigo plugins repositories. I don't know if they are still used ;-)

**Pull request merged**
